# Generated by Django 3.0.8 on 2020-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='newsTitle/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикаций')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
