from django.db import models


class Schedule(models.Model):
    class_of_lesson = models.CharField("Класс", max_length=3)
    start_firts_lesson_monday = models.CharField('(Понедельник) Начало 1 урока', max_length=11)
    end_firts_lesson_monday = models.CharField("Конец урока", max_length=11)
    first_lesson_monday = models.CharField("Урок", max_length=20)
    start_two_lesson_monday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_monday = models.CharField("Конец урока", max_length=11)
    two_lesson_monday = models.CharField("Урок", max_length=20)
    start_free_lesson_monday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_monday = models.CharField("Конец урока", max_length=11)
    free_lesson_monday = models.CharField("Урок", max_length=20)
    start_four_lesson_monday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_monday = models.CharField("Конец урока", max_length=11)
    four_lesson_monday = models.CharField("Урок", max_length=20)
    start_five_lesson_monday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_monday = models.CharField("Конец урока", max_length=11)
    five_lesson_monday = models.CharField("Урок", max_length=20)
    start_six_lesson_monday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_monday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_monday = models.CharField("Урок", max_length=20)
    start_seven_lesson_monday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_monday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_monday = models.CharField("Урок", max_length=20)
    start_firts_lesson_tuesday = models.CharField('(Вторник) Начало 1 урока', max_length=11)
    end_firts_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    first_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_two_lesson_tuesday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    two_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_free_lesson_tuesday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    free_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_four_lesson_tuesday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    four_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_five_lesson_tuesday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_tuesday = models.CharField("Конец урока", max_length=11)
    five_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_six_lesson_tuesday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_tuesday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_seven_lesson_tuesday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_tuesday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_tuesday = models.CharField("Урок", max_length=20)
    start_first_lesson_wednesday = models.CharField('(Среда) Начало 1 урока', max_length=11)
    end_first_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    first_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_two_lesson_wednesday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    two_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_free_lesson_wednesday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    free_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_four_lesson_wednesday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    four_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_five_lesson_wednesday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_wednesday = models.CharField("Конец урока", max_length=11)
    five_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_six_lesson_wednesday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_wednesday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_seven_lesson_wednesday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_wednesday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_wednesday = models.CharField("Урок", max_length=20)
    start_first_lesson_thursday = models.CharField('(Четверг) Начало 1 урока', max_length=11)
    end_first_lesson_thursday = models.CharField("Конец урока", max_length=11)
    first_lesson_thursday = models.CharField("Урок", max_length=20)
    start_two_lesson_thursday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_thursday= models.CharField("Конец урока", max_length=11)
    two_lesson_thursday = models.CharField("Урок", max_length=20)
    start_free_lesson_thursday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_thursday = models.CharField("Конец урока", max_length=11)
    free_lesson_thursday = models.CharField("Урок", max_length=20)
    start_four_lesson_thursday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_thursday = models.CharField("Конец урока", max_length=11)
    four_lesson_thursday = models.CharField("Урок", max_length=20)
    start_five_lesson_thursday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_thursday = models.CharField("Конец урока", max_length=11)
    five_lesson_thursday = models.CharField("Урок", max_length=20)
    start_six_lesson_thursday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_thursday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_thursday = models.CharField("Урок", max_length=20)
    start_seven_lesson_thursday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_thursday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_thursday = models.CharField("Урок", max_length=20)
    start_first_lesson_friday = models.CharField('(Пятница) Начало 1 урока', max_length=11)
    end_first_lesson_friday = models.CharField("Конец урока", max_length=11)
    first_lesson_friday = models.CharField("Урок", max_length=20)
    start_two_lesson_friday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_friday= models.CharField("Конец урока", max_length=11)
    two_lesson_friday = models.CharField("Урок", max_length=20)
    start_free_lesson_friday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_friday = models.CharField("Конец урока", max_length=11)
    free_lesson_friday = models.CharField("Урок", max_length=20)
    start_four_lesson_friday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_friday = models.CharField("Конец урока", max_length=11)
    four_lesson_friday = models.CharField("Урок", max_length=20)
    start_five_lesson_friday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_friday = models.CharField("Конец урока", max_length=11)
    five_lesson_friday = models.CharField("Урок", max_length=20)
    start_six_lesson_friday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_friday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_friday = models.CharField("Урок", max_length=20)
    start_seven_lesson_friday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_friday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_friday = models.CharField("Урок", max_length=20)
    start_first_lesson_saturday = models.CharField('(Суббота) Начало 1 урока', max_length=11)
    end_first_lesson_saturday= models.CharField("Конец урока", max_length=11)
    first_lesson_saturday = models.CharField("Урок", max_length=20)
    start_two_lesson_saturday = models.CharField('Начало 2 урока', max_length=11)
    end_two_lesson_saturday= models.CharField("Конец урока", max_length=11)
    two_lesson_saturday = models.CharField("Урок", max_length=20)
    start_free_lesson_saturday = models.CharField('Начало 3 урока', max_length=11)
    end_free_lesson_saturday = models.CharField("Конец урока", max_length=11)
    free_lesson_saturday = models.CharField("Урок", max_length=20)
    start_four_lesson_saturday = models.CharField('Начало 4 урока', max_length=11)
    end_four_lesson_saturday = models.CharField("Конец урока", max_length=11)
    four_lesson_saturday = models.CharField("Урок", max_length=20)
    start_five_lesson_saturday = models.CharField('Начало 5 урока', max_length=11)
    end_five_lesson_saturday = models.CharField("Конец урока", max_length=11)
    five_lesson_saturday = models.CharField("Урок", max_length=20)
    start_six_lesson_saturday = models.CharField('Начало 6 урока', max_length=11)
    end_six_lesson_saturday = models.CharField('Конец 6 урока', max_length=11)
    six_lesson_saturday = models.CharField("Урок", max_length=20)
    start_seven_lesson_saturday = models.CharField('Начало 7 урока', max_length=11)
    end_seven_lesson_saturday = models.CharField('Конец 7 урока', max_length=11)
    seven_lesson_saturday = models.CharField("Урок", max_length=20)



    def __str__(self):
        return self.class_of_lesson

    class Meta:
        verbose_name = "Расписание"
        verbose_name_plural = "Расписание"

