# Generated by Django 3.0.8 on 2020-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_of_lesson', models.CharField(max_length=3, verbose_name='Класс')),
                ('start_firts_lesson_monday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_firts_lesson_monday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('first_lesson_monday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_two_lesson_monday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_two_lesson_monday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('two_lesson_monday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_free_lesson_monday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_free_lesson_monday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('free_lesson_monday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_four_lesson_monday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_four_lesson_monday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('four_lesson_monday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_five_lesson_monday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_five_lesson_monday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('five_lesson_monday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_firts_lesson_tuesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_firts_lesson_tuesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('first_lesson_tuesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_two_lesson_tuesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_two_lesson_tuesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('two_lesson_tuesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_free_lesson_tuesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_free_lesson_tuesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('free_lesson_tuesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_four_lesson_tuesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_four_lesson_tuesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('four_lesson_tuesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_five_lesson_tuesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_five_lesson_tuesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('five_lesson_tuesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_first_lesson_wednesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_first_lesson_wednesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('first_lesson_wednesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_two_lesson_wednesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_two_lesson_wednesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('two_lesson_wednesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_free_lesson_wednesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_free_lesson_wednesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('free_lesson_wednesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_four_lesson_wednesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_four_lesson_wednesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('four_lesson_wednesday', models.CharField(max_length=20, verbose_name='Урок')),
                ('start_five_lesson_wednesday', models.CharField(max_length=11, verbose_name='Начало урока')),
                ('end_five_lesson_wednesday', models.CharField(max_length=11, verbose_name='Конец урока')),
                ('five_lesson_wednesday', models.CharField(max_length=20, verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
