# Generated by Django 3.0.8 on 2020-10-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_first_lesson_wednesday',
            field=models.CharField(max_length=11, verbose_name='(Среда) Начало 1 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_firts_lesson_monday',
            field=models.CharField(max_length=11, verbose_name='(Понедельник) Начало 1 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_firts_lesson_tuesday',
            field=models.CharField(max_length=11, verbose_name='(Вторник) Начало 1 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_five_lesson_monday',
            field=models.CharField(max_length=11, verbose_name='Начало 5 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_five_lesson_tuesday',
            field=models.CharField(max_length=11, verbose_name='Начало 5 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_five_lesson_wednesday',
            field=models.CharField(max_length=11, verbose_name='Начало 5 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_four_lesson_monday',
            field=models.CharField(max_length=11, verbose_name='Начало 4 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_four_lesson_tuesday',
            field=models.CharField(max_length=11, verbose_name='Начало 4 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_four_lesson_wednesday',
            field=models.CharField(max_length=11, verbose_name='Начало 4 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_free_lesson_monday',
            field=models.CharField(max_length=11, verbose_name='Начало 3 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_free_lesson_tuesday',
            field=models.CharField(max_length=11, verbose_name='Начало 3 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_free_lesson_wednesday',
            field=models.CharField(max_length=11, verbose_name='Начало 3 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_two_lesson_monday',
            field=models.CharField(max_length=11, verbose_name='Начало 2 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_two_lesson_tuesday',
            field=models.CharField(max_length=11, verbose_name='Начало 2 урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_two_lesson_wednesday',
            field=models.CharField(max_length=11, verbose_name='Начало 2 урока'),
        ),
    ]
